#pragma once

#define PIN_BUZZER 11
#define PIN_ENG_SPD_LEFT 10
#define PIN_ENG_SPD_RIGHT 9
#define PIN_ENG_DIR_LEFT 3
#define PIN_ENG_DIR_RIGHT 2
#define PIN_SENSOR_LEFT 15
#define PIN_SENSOR_RIGHT 14
#define PIN_SENSOR_REAR 36
#define PIN_HEAD_SENSOR_SERVO 17
#define PIN_HEAD_SENSOR_TRIGGER 7
#define PIN_HEAD_SENSOR_ECHO 8
#define PIN_THERMOMETER A3
